feat: add user and item
MayFoxes/java-shareit pull request #1
Opened 2024-04-26 20:16 UTC by MayFoxes

Созданные объекты Item и User.

2024-04-27 14:13 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара небольших замечаний!

Желаю удачи!

2024-04-27 14:13 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDto> findItemsByName(@RequestParam(name = "text") String text) {
Если параметр `name` совпадает с названием переменной, то в нем нет необходимости

2024-04-27 14:13 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +    }
Эта проверка пробегает по всем адресам электронной почты, а можно ли сделать ее эффективнее?

2024-04-27 15:58 UTC, MayFoxes commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +    }
Вероятно можно дополнительно хранить почту в отдельном месте и при проверке сверять на уникальность. Но я просто заменил на stream и возможно так менее эффективней.

2024-04-28 18:54 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-05-14 10:45 UTC, merged