Add bookings
MayFoxes/java-shareit pull request #2
Opened 2024-05-14 10:43 UTC by MayFoxes

Добавлена БД и ее реализация.
Добавлена реализация bookings и comment.

2024-05-15 07:49 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-05-15 07:49 UTC, LexLippi commented on src/main/resources/schema.sql
> +    TEXT        VARCHAR(2000) NOT NULL,
Лучше не называть колонку, как тип данных, а если делаем это, то стоит оборачивать название в \`\`

2024-05-15 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +class ItemRequest {
Модификатор доступа советовал бы оставить явным

2024-05-15 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return bookingItemsDto.get(0);
В таком случае лучше было бы написать с использованием Stream API:

```java
return bookingItemsDto.stream()
    .filter(dtoBooking -> dtoBooking.getStart().isAfter(LocalDateTime.now()) &&
        dtoBooking.getStatus().equals(BookingStatus.APPROVED))
    .findFirst()
    .orElse(null)
```

2024-05-15 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private BookingItemDto getLastBooking(List<BookingItemDto> bookingItemsDto) {
Аналогично замечанию ниже, с последним элементом это чуть сложнее, но тоже возможно

2024-05-15 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
Сделать приватным конструктор без аргументов

2024-05-15 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Item saveItem(@RequestHeader("X-Sharer-User-Id") Long ownerId,
Строку `"X-Sharer-User-Id"` можно вынести в константу класса или проекта

2024-05-15 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/comment/dto/CommentMapper.java
> +public class CommentMapper {
Сделать приватным конструктор без аргументов

2024-05-15 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (approved) {
Можно использовать тернарный оператор

2024-05-15 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!booking.getItem().getOwner().equals(itemOwnerId))
Советую следовать Google Java Code Style в отношении опциональных скобок:

https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2024-05-15 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +public class BookingMapper {
Сделать приватным конструктор без аргументов

2024-05-15 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                            @RequestParam(required = false, defaultValue = "ALL") String state) {
`required = false` устанавливается автоматически, когда выставляешь параметр `defaultValue`, так что в явном его использовании нет смысла, касается всех таких ситцаций в этом файле

2024-05-15 10:00 UTC, MayFoxes commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
Использовал аннотацию @UtilityClass

2024-05-16 10:34 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-05-17 14:56 UTC, merged