fw 16: add docker
MayFoxes/java-shareit pull request #4
Opened 2024-06-07 22:10 UTC by MayFoxes

2024-06-09 18:05 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пара замечаний, которые необходимо исправить!

Желаю удачи!

2024-06-09 18:05 UTC, LexLippi commented on server/src/main/resources/schema.sql
> +    CREATED     TIMESTAMP,
А почему здесь ограничение `not null` убрал?
Как и собственно везде выше?

2024-06-09 18:05 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/request/RequestController.java
> +            @Positive @RequestParam(value = "size", required = false) Integer size,
1.  Не имеет смысла поле `value`, если оно совпадает с названием переменной
2. Почему где-то у этих полей есть `defaultValue`, а где-то нет? Хотелось бы большего единообразия

2024-06-09 18:05 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +        return !(start.equals(end) || end.isBefore(start));
Можно упростить метод:

```java
return start != null && end != null && end.isAfter(start);
```

2024-06-09 19:10 UTC, MayFoxes commented on server/src/main/resources/schema.sql
> +    CREATED     TIMESTAMP,
Когда прочитал, что нужно убрать валидацию в модуле server, то воспринял это слишком буквально.

2024-06-09 19:41 UTC, MayFoxes commented
Исправил замечания

2024-06-11 08:00 UTC, kesch9 approved these changes
Approve

2024-06-11 08:00 UTC, kesch9 commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                     @RequestParam(defaultValue = "10") Integer size,
Можно лучше
можно было не указывать defaultValue, gateway и так проставит их если не будет их в запросе. Также можно вместо строк использовать сразу enum и вместо строки String state, принимать BookingState state

2024-06-11 08:00 UTC, kesch9 commented on server/src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "START_TIME")
Для Column также не надо было убирать nullable как и в скриптах. Но вы восстановили в скриптах, хотя бы на уровне БД будет валидация

2024-06-11 10:13 UTC, merged